version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - database

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
