name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME_BACKEND: mustafabaig/backend
  IMAGE_NAME_FRONTEND: mustafabaig/frontend

jobs:
  build-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Image
        run: |
          docker build -t $IMAGE_NAME_BACKEND:${{ github.sha }} ./backend

      - name: Run Backend Unit Tests
        run: |
          docker run --rm $IMAGE_NAME_BACKEND:${{ github.sha }} npm test

      - name: Lint Backend Code
        run: |
          docker run --rm $IMAGE_NAME_BACKEND:${{ github.sha }} npm run lint

  build-frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend Image
        run: |
          docker build -t $IMAGE_NAME_FRONTEND:${{ github.sha }} ./frontend

      - name: Run Frontend Unit Tests
        run: |
          docker run --rm $IMAGE_NAME_FRONTEND:${{ github.sha }} npm test

      - name: Lint Frontend Code
        run: |
          docker run --rm $IMAGE_NAME_FRONTEND:${{ github.sha }} npm run lint

  security-scan:
    name: Run Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: 0

  push-to-dockerhub:
    name: Push Images to DockerHub
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Backend Image
        run: |
          docker tag $IMAGE_NAME_BACKEND:${{ github.sha }} $REGISTRY/$IMAGE_NAME_BACKEND:${{ github.sha }}
          docker tag $IMAGE_NAME_BACKEND:${{ github.sha }} $REGISTRY/$IMAGE_NAME_BACKEND:latest
          docker push $REGISTRY/$IMAGE_NAME_BACKEND:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME_BACKEND:latest

      - name: Push Frontend Image
        run: |
          docker tag $IMAGE_NAME_FRONTEND:${{ github.sha }} $REGISTRY/$IMAGE_NAME_FRONTEND:${{ github.sha }}
          docker tag $IMAGE_NAME_FRONTEND:${{ github.sha }} $REGISTRY/$IMAGE_NAME_FRONTEND:latest
          docker push $REGISTRY/$IMAGE_NAME_FRONTEND:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME_FRONTEND:latest

